# Generated by Django 5.1 on 2024-08-27 03:18

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='schedule',
            field=models.TimeField(default='12:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='run',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.job'),
            preserve_default=False,
        ),
    ]
