# Generated by Django 5.1 on 2024-08-27 04:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_schedule_run_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='completed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='run',
            name='started',
            field=models.DateTimeField(),
            preserve_default=False,
        ),
    ]
