# Generated by Django 5.1 on 2024-08-27 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0003_run_completed_run_started"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="deployTo",
            field=models.ManyToManyField(to="jobs.deploydestination"),
        ),
    ]
