# Generated by Django 5.1 on 2024-08-27 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_job_deployto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='run',
            options={'get_latest_by': 'started'},
        ),
        migrations.AlterField(
            model_name='run',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='jobs.job'),
        ),
    ]
