# Generated by Django 5.1 on 2024-08-27 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_alter_run_options_alter_run_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='started',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
