# Generated by Django 5.1 on 2024-08-27 23:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_alter_run_started'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='scheduled',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 27, 23, 35, 15, 404277, tzinfo=datetime.timezone.utc)),
        ),
    ]
