# Generated by Django 5.1 on 2024-08-28 20:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_run_scheduled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='scheduled',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
