# Generated by Django 5.1 on 2024-08-28 20:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_alter_run_scheduled'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scheduler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastSuccessfulScheduling', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
