# Generated by Django 5.1 on 2024-08-28 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_rename_scheduler_scheduling_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
