# Generated by Django 5.1 on 2024-08-29 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_alter_run_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('association', models.CharField(choices=[('L', 'Preload'), ('B', 'Prebuild'), ('D', 'Predeploy'), ('N', 'Prenotify'), ('O', 'Oncomplete')], default='B', max_length=1)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='jobs.job')),
            ],
        ),
    ]
